### ISSUE TITLE
Provided certificate is not valid for encryption/decryption.

### ISSUE THREAD

**Issue by travisjs** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#1]
Received this error when trying to run sample project, i.e. TestClient.

`Provided certificate is not valid for encryption/decryption. There may be insufficient permissions to its private key in the windows certificate store or the certificate itself may not have the correct purposes. If you only want to use it for signing, set the Use property to Signing (CertificateUse.Signing).`

Happens on Startup.cs when trying to add the testclient.pfx certificate.

```
Line 26:                 AuthenticateRequestSigningBehavior = SigningBehavior.Always
Line 27:             };
Line 28:             spOptions.ServiceCertificates.Add(new X509Certificate2(HostingEnvironment.MapPath("~/testclient.pfx"), "test"));
Line 29: 
Line 30:             var options = new KentorAuthServicesAuthenticationOptions(false)
```

Tried the following

- Adding pfx file to Personal and Trusted Root stores
- Gave all users/accounts (system or otherwise) full control to folder and pfx file
- Changed code as follows:

```
            var cert = new X509Certificate2(HostingEnvironment.MapPath("~/testclient.pfx"), "test");

            var serviceCertificate = new ServiceCertificate
            {
                Certificate = cert,
                Use = CertificateUse.Signing
            };

            var spOptions = new SPOptions
            {
                EntityId = new EntityId("http://localhost:50155/AuthServices"),
                AuthenticateRequestSigningBehavior = SigningBehavior.Always,
                ServiceCertificates = { serviceCertificate }
            };

            //spOptions.ServiceCertificates.Add(new X509Certificate2(HostingEnvironment.MapPath("~/testclient.pfx"), "test"));
```

But that yields another error:  CryptographicException: Invalid provider type specified.

**Comment by scottbrady91** [comment]
Hi, looks like the wrong test signing certificate for the example client app was uploaded. I'll update shortly.

**Comment by scottbrady91** [comment]
Okay, I've tweaked the certificates and specified that keys should only be used for signing (and never for encryption which was causing the initial error). This stuff makes me miss makecert...

Let me know how it goes.

**Comment by travisjs** [comment]
Yes, it is working now, though I had to change the port number in the IdentityProvider options in the TestClient to 51577 to match the IdSvr project. (I think I've used 5000 far too many times).

And yes, certificates are still a bit mysterious to me, just when I think I've got them figured out, something new comes up.

Thanks!

**Comment by scottbrady91** [comment]
Awesome, glad to hear it
