### ISSUE TITLE
HttpPost Logout response

### ISSUE THREAD

**Issue by Baranitharan84** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#10]
With the latest release on Rsk.IdentityServer4.Saml version 2.2, I'm seeing the below note:
**Added full support for redirect and post bindings**
**Added SP-initiated logout**

So shall I assume that Single Logout SAML response will be posted from Idp to service provider wtih HttpPost binding? If so, can you provide us some sample code on how to achieve that?

**Comment by scottbrady91** [comment]
As discussed via email, Logout requests sent from an SP are now supported, however IdP's sending Logout responses won't be supported until the next major version.
