### ISSUE TITLE
Where do I get a valid LicenseKey & Licensee

### ISSUE THREAD

**Issue by jongear** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#11]
The provided `Licensee` and `LicenseKey` are empty in the sample repo which causes the following runtime failure 

![image](https://user-images.githubusercontent.com/8430731/53188777-b0104400-35cb-11e9-8d79-14dfe4855cbf.png)

**Comment by jongear** [comment]
Is a license required to use this plugin? Or purely to use RSK's SAML 2.0 Federation Gateway offering? https://www.identityserver.com/products/

**Comment by jandieg** [comment]
Hi, I'm also stuck here. Is this a commercial feature?

**Comment by jongear** [comment]
I realized this is a commercial product. In order to get a license key, you need to contact sales.
