### ISSUE TITLE
Accepted RequestTrustLength Value

### ISSUE THREAD

**Issue by Baranitharan84** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#13]
Hi,

We have 2 pages for user registration in our IdentityServer4 IDP application and sometimes if user takes more than 2 minutes to fill the form, we are getting the following error. 

I noticed this timespan property "**RequestTrustLength**" in SamlIdpOptions.

If I set some value for this property, will it fix my issue? 
If so, what would be the maximum value I can go for it?
Does it cause any security issues if I bump the value to say 20 minutes?

I wonder what would be optimum way to fix this issue.

```
2019-04-30 12:12:46.000 -05:00 [SSOIDP] [ERROR] IdentityServer4.Saml.Validation.Saml2SingleSignOnRequestValidator [0HLMDHH7MSK5M:00000004]  - SAMLRequest IssueInstant too old to trust
{
  "SubjectId": "a484f725-fb3d-4690-ab67-8f759b2fa5e1",
  "BindingType": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
  "RelayState": "c1c2b43d-f9c5-4313-a477-4ea3f1b45dfb",
  "SignatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha512"
}
```

**Comment by scottbrady91** [comment]
Yes, by increasing the value of this property you will be able to fix your issue.

The value to use would depend on your use case, and yes, a longer value does create a security risk as it gives an attacker more time to steal SAML assertions and inject them into your app, maybe even replaying them.

If the user is going to be spending a lot of time registering in between the initial authentication request and signing in, I would recommend restarting the auth process.

**Comment by Baranitharan84** [comment]
Thank you Scott. 
We will try to keep that value as minimum as we can.
