### ISSUE TITLE
Can we provide the username to ADFS via the SAML Auth Request?

### ISSUE THREAD

**Issue by wolfen351-diligent** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#16]
Hi there

I found this request in the Azure Ad Issues https://github.com/MicrosoftDocs/azure-docs/issues/19654 and this part of the SAML Spec - https://www.oasis-open.org/committees/download.php/35711/sstc-saml-core-errata-2.0-wd-06-diff.pdf (See 3.4.1).

It implies that there is a way to tell ADFS via SAML that we would like to login as a particular subject.

Is this possible? What parameter should we set on the request to add this data to the SAML ?

**Comment by scottbrady91** [comment]
Hi! Sorry about the delay. For future questions regarding the component, please email support@identityserver.com for faster response times.

I think I may have already answered your question (or your colleagues) via the help desk, but currently, this is not something we support (and for some reason discouraged by previous versions of the interoperability specification (https://saml2int.org/profile/current/#section82).

I don't believe that this is supported by ADFS either.

**Comment by wolfen351-diligent** [comment]
Thanks for the clear answer!
