### ISSUE TITLE
Adding Extra Attribute for SAMLRequest

### ISSUE THREAD

**Issue by sombek** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#17]
Greetings,

I want to add one more attribute to SAMLRequest:
``` text
https://localhost:8080/samlsso?SAMLRequest=fJFPb8IwDMW%2FSpV727SlBSxAYuMwJKYh2u2wy5SmEURqnS5Oxz7%2Bwj9pXDjafj%2FrPXtGomvTHpaDO%2BBOfQ%2BKXPDbtUhwmczZYBGMIE2AolMETkK5fN1AGnHorXFGmpb9Zx4jgkhZpw2yYL2as6%2BimIzkJKvzUdGM8jqdJtM6S%2BRYjtVYyqxhwYey5PVz5nEPEQ1qjeQEOt%2FiKQ95FiZFxaeQJ8D5JwtWPoVG4c7UwbmeII6Px2OkRReRiE82iQwLljczzwZp6JQtlf3RUr3vNhfQc62Roj0YcpBzzmPSe9QYnlawYHvN%2F6Sx0bh%2FnLy%2BiAheqmobbt%2FKii1m54vBOZRd3Kz2VvnLNqHoe4qsarznWXynvJb3j1v8AQAA%2F%2F8DAA%3D%3D&RelayState=zF43mWwSY1nDuAl5LVpLJgsr&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=YHTen21lr3JFtIRp2YdXCDE6g6Q%2FnVnzc0m3UISxU%2FBSq%2B5nPRs6doGmRnKW33sLcZM6L2I34AWcoh4eD03jD%2BnITZzKaF0DOUeY8hRs7RiP4GG22OjGqJjz7CUO2q3WT8HfC709WAreTqdktu296haZZUp2tqOpNj0%2BpwxDFQs5oOMfJIEsbLavzuINfTgba04vQr1CkdMpQz2NFM9HONIZ8uSFhxWPiE6tqSBJqHodHpK2j9Sf5SJPGFHrQ3VA8XuWbNCZoxFlCJqmzpZj8lpIQIsiW1U8CY1MY3vzPQ3kkWpJvUqClA87aPNUOHfDE2%2FW9YaelRGjOO%2FwqXs4Sg%3D%3D
```
I want to add ``&lang=ar`` to the above request.

I couldn't find anything that could help me to find a trace for this thing.
It happens right after calling this endpoint ``External/Challenge``

**Comment by scottbrady91** [comment]
From your support ticket:

> Hi Abdullah,
> 
> Unfortunately, adding custom parameters is not something we support in our component.
> 
> My suggestion would be to create middleware that can intercept our SAML response and add the extra query parameter. By default, SAML responses are only returned from a path beginning with /saml/sso.
> 
> Otherwise, you could consider overriding our "Saml2SingleSignOnResponseGenerator" with your own implementation that adds your custom values to the response, however, I would say that this is more effort than the middleware approach.
> 
> Please note, that no matter which approach you use, these extra values will not be included in signature generation/validation.
> 
> Thanks,
> 
> Scott.

**Comment by sombek** [comment]
@scottbrady91 
Thanks for your response.
I have been investigating since yesterday, and I will write what I understood. And correct me if I am taking a wrong approach please 🙂

What I want is to override this function:
``IdentityServer4.Saml.Services.SamlBindingService.CreateRedirectBindingQueryString``

``` c#
  public async Task<string> CreateRedirectBindingQueryString(RedirectBindingRequest request)
    {
      /*
       * The original code
       */

      if (!string.IsNullOrWhiteSpace(request.RelayState))
        queryString = queryString + "&RelayState=" + Uri.EscapeDataString(request.RelayState);
      if (request.RequiresSigning)
      {
        queryString = queryString + "&SigAlg=" + Uri.EscapeDataString(request.SignatureAlgorithm);
        queryString = queryString + "&Signature=" + await this.signingService.CreateRedirectBindingSignature(queryString, request.SigningCertificate, (SigningOptions) null);
      }
      // ##########
      // I want to add only this line here
      queryString = queryString + "&lang=ar";
      // ##########

      return queryString;

    }
```

My question is how would I override this function to be used from the application level. Since this code is decompiled code from the IDE. 

Thanks,
Abdullah

**Comment by sombek** [comment]
Any Response?

**Comment by sombek** [comment]
I fixed it by using middleware

See below snippet maybe it helps someone else 
```c#
// in startup.cs file
app.Use(async (httpcontext, next) => {
    await next();
    string location = httpcontext.Response.Headers[Microsoft.Net.Http.Headers.HeaderNames.Location];
    if (location.Contains("SAMLRequest")) {
        httpcontext.Response.Headers[Microsoft.Net.Http.Headers.HeaderNames.Location] = location + "&lang=ar";
    }
});

```

Thanks 👍
