### ISSUE TITLE
What is the difference between the projects?

### ISSUE THREAD

**Issue by verzada** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#18]
I find the ReadMe.md a bit lacking. Could you elaborate more?

What is IDP?
I understand the other option is IDP with Entity Framework.

What is SP? Is it service provider?
SP with IDP initiated .. what does that mean?

Why would you choose on project over another?

**Comment by scottbrady91** [comment]
Hi!

Sorry, this repo does require some level of SAML knowledge to navigate. Materials explaining SAML itself are something we are working on, but in the meantime:

An **Identity Provider (IdP)** is someone who will receive SAML requests, authenticate users, and return SAML responses & assertions.

A **Service Provider (SP)** is someone who sends SAML requests to an IdP, will receive SAML responses, and potentially create a session for the user described in the assertion. In the OpenID Connect world, this would be comparable to a client application.

**Comment by verzada** [comment]
Yeah, I cannot say I'm an expert with all things SAML, learning it now.

But that's why it would be great to have some pointers to what the projects solve.
