### ISSUE TITLE
SAML Authentication for REST APIs and SPA applications

### ISSUE THREAD

**Issue by bomman** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#19]
Hi guys,

I recently got demo license to test SAML2P integration with IdentityServer4. I got it working with IdP and SP. My goal is to create SSO functionality with a single IdP for API, SPA, MVC applications. This IdP should also have the functionality to issue JWT using PKCE or client credentials authorization flow.

So, I want to continue investigating it for authentication for REST APIs. I found it one issue from 2018 that @scottbrady91  has commented that SAML authentication for REST APIs is not possible. If not, is it possible to use some combination between SAML and OAuth and OIDC? Do I need to save the JWT token in the SAML cookie? Are there some best practices?

Looking forward to get a feedback from you.

**Comment by scottbrady91** [comment]
From support@identityserver.com:

Reply 1:
> Unfortunately, SAML is not designed for modern application types such as SPAs or mobile applications, so I wouldn't recommend using SAML for your SSO in this scenario. SAML also does not have a concept of API protection, so it cannot protect your APIs.

> However, since you are using IdentityServer4, you can use a combination of OAuth and OpenID Connect for these application types and for your APIs. These protocols work alongside SAML and will share an SSO session.

Reply 2:

> For general IdentityServer usage, I would recommend checking out the quickstart documentation. This includes walkthroughs on both API protection and SSO with a SPA https://identityserver4.readthedocs.io/en/latest/quickstarts/4_javascript_client.html.

> The SPA walkthrough uses a library written in plain JavaScript, so it can work with any SPA framework.

> Using this approach, you can still use our SAML component to both federate with an external identity provider or to allow legacy SAML apps to use your new IdentityServer solution.
