### ISSUE TITLE
Multi-tenant support

### ISSUE THREAD

**Issue by narbit** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#20]
Samples indicate that multiple IDPs are supported. Is configuration for such scenarios done entirely in code? Are any other configuration modes supported?

**Comment by scottbrady91** [comment]
Hi! Yes, when acting as an SP, you have to configure this in code. This is a limitation of all ASP.NET Core authentication handlers and is the same for the OpenID Connect and WS-Federation handlers from Microsoft.

However, we do have a product that allows you to configure ASP.NET Core authentication handlers from a database, call Dynamic Authentication Providers https://www.identityserver.com/products/dynamic-authentication-providers

For further component support, please email support@identityserver.com.
