### ISSUE TITLE
SAML  unsigned request to IDP - WantAuthenticationRequestsSigned

### ISSUE THREAD

**Issue by frjaffery** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#21]
If we allow service provider(s) to send unsigned request to IDP, what are the risks? please let me know your thoughts.

**Comment by scottbrady91** [comment]
Handled via email:

> Without requiring signed requests, an attacker could generate their own SAML requests and cause your SAML IdP to generate assertions for a user. This may contain PII, which could be mitigated using assertion encryption. However, if the SAML SP is validating assertions correctly and only allows SP-Initiated SSO, then the attacker will not be able to use the assertion to create a session within the IdP.

> OAuth and OpenID Connect typically do not typically require signed/authenticated requests to their authorization endpoints.
