### ISSUE TITLE
invalid acs url reported

### ISSUE THREAD

**Issue by gvchoudaryenator** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#24]
I hosted the saml2p SP application in azure with out any dns binding but, the requests comes from the azure gateway with sub domain to SP.while SP application trying to navigate to the IDP for Authentication it is showing as "Invalid ACS URL" error.

The Idp has two SP's configured as below one with subdomain & other with default azure url
gateway request URL : spagw.test.com (this is not working)

**below are 2 SPs configured at SAML2p IDP server**
```
 new ServiceProvider
 {
                    EntityId = "https://spagw.test.com/saml",
                    AssertionConsumerServices =
                        {new Service(SamlConstants.BindingTypes.HttpRedirect, "https://spagw.test.com/signin-saml")},
                    SigningCertificates = {new X509Certificate2("myCert2020.cer") }
}
```

```
new ServiceProvider
{
                    EntityId = "https://test-sp-portal-web.azurewebsites.net/saml",
                    AssertionConsumerServices =
                        {new Service(SamlConstants.BindingTypes.HttpPost, "https://test-sp-portal-web.azurewebsites.net/signin-saml")},
                    SigningCertificates = {new X509Certificate2("myCert2020.cer") }
}
```

IDP configuration at SP portal

 
IDP1

     .AddSaml2p("idp1", options => {
                 options.Licensee = "TEST";
                 options.LicenseKey = "LicenseKey";

                 options.IdentityProviderOptions = new IdpOptions
                 {
                     EntityId = ssoSettings.SamlSSO,
                     SigningCertificates = new List<X509Certificate2> { new X509Certificate2(Convert.FromBase64String(@"MIIGSzCCBTOgAwIBAgIJAJbzTeuezhBtMA0GCSqGSIb3DQEBCwUAMIG0MQswCQ")) },
                     SingleSignOnEndpoint = new SamlEndpoint("https://idp.myidpserver.com/saml/sso", SamlBindingTypes.HttpPost),
                     SingleLogoutEndpoint = new SamlEndpoint("https://idp.myidpserver.com/saml/sso", SamlBindingTypes.HttpPost),

                 };

                 options.ServiceProviderOptions = new SpOptions
                 {
                     EntityId = "https://test-sp-portal-web.azurewebsites.net/saml",
                     MetadataPath = "/saml/metadata",
                     SignAuthenticationRequests = true,
                  
                     SigningCertificate = new X509Certificate2("myCert2020.pfx", "pfxpassword@123")
                 };

                 options.NameIdClaimType = "sub";
                 options.CallbackPath = "/signin-saml";
                 options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                
                 // IdP-Initiated SSO
                 options.AllowIdpInitiatedSso = true;
                 options.IdPInitiatedSsoCompletionPath = "/";
             })
```
IDP2

     .AddSaml2p("idp2", options => {
                 options.Licensee = "TEST";
                 options.LicenseKey = "LicenseKey";

                 options.IdentityProviderOptions = new IdpOptions
                 {
                     EntityId = ssoSettings.SamlSSO,
                     SigningCertificates = new List<X509Certificate2> { new X509Certificate2(Convert.FromBase64String(@"MIIGSzCCBTOgAwIBAgIJAJbzTeuezhBtMA0GCSqGSIb3DQEBCwUAMIG0MQswCQ")) },
                     SingleSignOnEndpoint = new SamlEndpoint("https://idp.myidpserver.com/saml/sso", SamlBindingTypes.HttpRedirect),
                     SingleLogoutEndpoint = new SamlEndpoint("https://idp.myidpserver.com/saml/sso", SamlBindingTypes.HttpRedirect),

                 };

                 options.ServiceProviderOptions = new SpOptions
                 {
                     EntityId = "https://spagw.test.com/saml",
                     MetadataPath = "/saml/metadata",
                     SignAuthenticationRequests = true,
                  
                     SigningCertificate = new X509Certificate2("myCert2020.pfx", "pfxpassword@123")
                 };

                 options.NameIdClaimType = "sub";
                 options.CallbackPath = "/signin-saml";
                 options.SignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                
                 // IdP-Initiated SSO
                 options.AllowIdpInitiatedSso = true;
                 options.IdPInitiatedSsoCompletionPath = "/";
             })

Above both SP requests goes to the same IDP but as a different clients

how to resolve the subdomain requests with out binding it to host? which is not originally binded to application

### SAML is generated like below



<EntityDescriptor ID="_cc5d1b6f-4ff3-43d6-9b6b-fce2682418ce" entityID="https://idp.myidpserver.com/saml" 
p1:saml2="urn:oasis:names:tc:SAML:2.0:assertion" cacheDuration="PT1H" xmlns:p1="xmlns" xmlns="urn:oasis:names:tc:SAML:2.0:metadata">

<SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"><SingleLogoutService 
Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://test-sp-portal-web.azurewebsites.net/" />

<SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" 
Location="https://test-sp-portal-web.azurewebsites.net/" />

<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
 Location="https://test-sp-portal-web.azurewebsites.net/signin-saml" index="1" />
 
 <AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
  Location="https://test-sp-portal-web.azurewebsites.net/signin-saml" index="2" />
  </SPSSODescriptor>
  
  </EntityDescriptor>


but the url's in SAML should be **https://idp.myidpserver.com** instead of  **https://test-sp-portal-web.azurewebsites.net**

**Comment by scottbrady91** [comment]
Hi! This issue tracker is for bugs with the GitHub samples. For component support, please could you send this to support@identityserver.com? A member of our SAML team will then get back to you ASAP.
