### ISSUE TITLE
access_token is always null 

### ISSUE THREAD

**Issue by gvchoudaryenator** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#25]
Our Identity server is updated with SAML2p and the existing client is updated as below SAML CLIENT 

// SAML client
                new Client
                {
                    ClientId = "http://localhost:7002/saml",
                    ClientName = "RSK SAML2P Test Client",
                    ProtocolType = IdentityServerConstants.ProtocolTypes.Saml2p,
                    AllowedScopes = new List<string>()
                    {
                        "api-auth",
                        "api-provider",
                        "api-documents",
                        IdentityServerConstants.StandardScopes.OpenId,
                        IdentityServerConstants.StandardScopes.Profile,
                        IdentityServerConstants.StandardScopes.OfflineAccess
                    },
                    AlwaysIncludeUserClaimsInIdToken = true,
                    AllowAccessTokensViaBrowser = true,
                    //Access token life time is 86400 seconds (24 hour)
                    AccessTokenLifetime = (configuration.AccessTokenLifetime == 0) ? 86400 : configuration.AccessTokenLifetime,
                    //Identity token life time is 86400 seconds (24 hour)
                    IdentityTokenLifetime = (configuration.IdentityTokenLifetime == 0) ? 86400 : configuration.IdentityTokenLifetime,
                },

// SP
                new ServiceProvider
                {
                    EntityId = "http://localhost:7002/saml",
                    AssertionConsumerServices =
                        {new Service(SamlConstants.BindingTypes.HttpPost, "http://localhost:7002/signin-saml")},
                    SigningCertificates = {new X509Certificate2("testclient.cer")},
                    ClaimsMapping = new Dictionary<string, string>
                                    {
                                        { JwtClaimTypes.Name, "Name" },
                                        { JwtClaimTypes.GivenName, "GivenName" },
                                        { JwtClaimTypes.FamilyName, "FamilyName" },
                                        { JwtClaimTypes.Email, "Email" }
                                    }
                },
After successfully authentication with SP, but access_token is always null to pass the token for API authentication, can you suggest a way to achieve this.
**FOR COMPONENT SUPPORT, PLEASE EMAIL support@identityserver.com**

**Comment by scottbrady91** [comment]
Hi! This issue tracker is for bugs in our GitHub samples. For component support, please could you send this to support@identityserver.com? A member of our SAML team will then get back to you ASAP.
