### ISSUE TITLE
SingleSignOnEndpoint with a question results in an invalid challenge URI

### ISSUE THREAD

**Issue by nikoudel** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#32]
When [SamlSingleSignOnEndpoint URI](https://github.com/RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration/blob/7f2b952d4712e2dabc955bd230facb18598e669f/IdentityServer4/sp/Startup.cs#L51) contains a query with a question mark, the resulting challenge URI will be invalid.

For example, [PingOne sign-in URL](https://support.pingidentity.com/s/article/PingOne-How-to-configure-SP-initiated-SSO) is constructed like this:

`https://sso.connect.pingidentity.com/sso/idp/SSO.saml2?idpid=<idpid>`

In that case the resulting challege will be rejected by the IdP as invalid:
![image](https://user-images.githubusercontent.com/1636683/107005219-17633680-6798-11eb-94f5-822a6a931b0e.png)

**Comment by scottbrady91** [comment]
From support@identityserver.com:

> We do not support extra query string parameters when using the HTTP Redirect binding, as this can cause issues when signing protocol messages.
> 
> Customers like yourself typically switch to using the HTTP POST binding, as this does not have the same concerns around compatibility.
> 
> I hope that helps.
