### ISSUE TITLE
Identity Server 4 (IDS4) as SAML SP Invalid redirect_uri

### ISSUE THREAD

**Issue by binbsr** [RockSolidKnowledge/Samples.IdentityServer4.Saml2pIntegration#4]
I am having hard time trying to make mvc app client (port 7000) to connect to IDS4 SAML SP which in turn federates to IDS4 SAML IDP to authenticate. I am using demo license for the plugin provided by RSK team.

Needed Scenario: ASP.NET Core APP ---talks--> IDS4 SAML SP ---talks--> IDS4 SAML IDP

Error I am getting:
```
Invalid redirect_uri: http://localhost:7000/signin-oidc
{
  "ClientId": "mvc",
  "ClientName": "MVC Client",
  "AllowedRedirectUris": [
    "http://localhost:5001/signin-oidc"
  ],
  "SubjectId": "anonymous",
  "RequestedScopes": "",
  "Raw": {
    "client_id": "mvc",
    "redirect_uri": "http://localhost:7000/signin-oidc",
    "response_type": "code id_token",
    "scope": "openid profile",
    "response_mode": "form_post",
    "nonce": "636703668912386576.MjNhODAxMmEtZDMzZS00ODFlLWJlNmMtMmQwODEwOTczOTIwM2VjZDE3NzMtZWY0OC00ZmUwLTk4YWMtOTc2OWU4MTM5ZWU3",
    "state": "CfDJ8IwNdcCHadNNga7v1HYQ8uVdzW4PxgMRT-Sz6hktJlP47BVoAzfJHGRiMqXkiCmcvNwefKmVGjFcVn2QyFRY04nHk0OBB_n7-JQ6QcEluUldNSHN-TnD4yCYrLbM_hrP89qZdclxIwrjVry9cgoRI_XEYqoiTK4XvTn8MlgeGevDs4i2q3HSN1CtddLm0OSMQ7-rnLe1DXT9gxydgKJbBLNbkMLXTkn6g7cSlk2cBM-oak3Pv5DQpcZYdN-waoZLVmbJX4RCLh9j3zQLYMnBuAvZAlXiVTFFCekfSTK6LWmSF9kOUlOIZrqQq8DxUPOVrw",
    "x-client-SKU": "ID_NETSTANDARD1_4",
    "x-client-ver": "5.2.0.0"
  }
}
```

ASP.NET Core MVC client is configured as:
```
services.AddAuthentication(options =>
            {
                options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = "oidc";
            })
.AddOpenIdConnect("oidc", options =>
                {
                    options.Authority = "http://localhost:5001";
                    options.RequireHttpsMetadata = false;
                    options.ClientId = "mvc";
                    options.ResponseType = "code id_token";
                    options.ClientSecret = "49C1A7E1-0C79-4A89-A3D6-A37998FB86B0";

                    options.Scope.Clear();
                    options.Scope.Add("openid");
                    options.Scope.Add("profile");

                    //options.SaveTokens = true;
                    //options.GetClaimsFromUserInfoEndpoint = true;

                    options.TokenValidationParameters = new TokenValidationParameters
                    {
                        NameClaimType = "name",
                        RoleClaimType = "role",
                    };
            })
```
And SP and IDP are as provided on this repo. Please help.

**Comment by scottbrady91** [comment]
Looks like you OIDC client application is configured with the wrong redirect URI.

You are asking for `http://localhost:7000/signin-oidc` but your IdentityServer is expecting `http://localhost:5001/signin-oidc` in its `AllowedRedirectUris`.

**Comment by binbsr** [comment]
Thanks @scottbrady91 !

Is port 5001 hard-coded (for demo license, also change on clientId complains) OIDC client. SP is also on 5001. So I tried:
1. Changed mvc client config on SP:
 ```
RedirectUris = {"http://localhost:5001/signin-oidc"},
FrontChannelLogoutUri="http://localhost:5001/signin-oidc",
PostLogoutRedirectUris={"http://localhost:5001/signout-callback-oidc"}
```
Its same previous error on question.

2. Changed SP port to other than 5001, and OIDC client on 5001.
Here, OIDC Client connects successfully to SP but now IDP complains: May be its expecting SP to run on same old 5001 port.
  
```
[20:14:41 Error] IdentityServer4.Saml.Validation.Saml2SingleSignOnRequestValidator
Unrecognized SAML service provider
{
  "SubjectId": "anonymous",
  "BindingType": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
  "RelayState": "G8U98F7k-G2vLgfgthnTOSRl",
  "SignatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
}

[20:14:41 Error] IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint
Request validation failed

[20:14:41 Error] IdentityServer4.Saml.Endpoints.Saml2SingleSignOnEndpoint
Request validation failed
{
  "SubjectId": "anonymous",
  "BindingType": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect",
  "RelayState": "G8U98F7k-G2vLgfgthnTOSRl",
  "SignatureAlgorithm": "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
}
```
Scott, would you mind telling me what am I missing?

**Comment by binbsr** [comment]
@scottbrady91 Any insight on this? My colleague (Samir Karki) already exchanging mails with you (and your team) and have plan to purchase the SAML2P plugin once done with POCs. But its really hard time getting things work.

**Comment by scottbrady91** [comment]
Changing the port numbers is fine, but they must match between your client applications and your identity providers. Licensing for the SAML component has no constraints on URLs used.

For the SAML error, this again sounds like ports not matching. Can you confirm that your SP is running on port 4000?

It might be worthwhile moving to our support channel for this, and sending in both your SP and IdP Metadata documents. You can send these to support@identityserver.com

**Comment by binbsr** [comment]
Yes, IDS4 SP is configured to 4000 and OIDC MVC app is connecting fine with it. I will forward this to support with metadata you requested. Thanks @scottbrady91!

**Comment by scottbrady91** [comment]
No problem!
